<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# 2D Numpy in Python    

## Objectives

After completing this lab you will be able to:

* Operate comfortably with `numpy`
* Perform complex operations with `numpy`


<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#Create-a-2D-Numpy-Array">Create a 2D Numpy Array</a></li>
        <li><a href="#Accessing-different-elements-of-a-Numpy-Array">Accessing different elements of a Numpy Array</a></li>
        <li><a href="#Basic-Operations">Basic Operations</a></li>
    </ul>
  
</div>

<hr>


## Create a 2D Numpy Array


In [1]:
# Import the libraries

import numpy as np

Consider the list <code>a</code>, which contains three nested lists **each of equal size**. 


In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

We can cast the list to a Numpy Array as follows:


In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank. 


In [4]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# checking the data type of the values in the array
print(A.dtype)

int32


Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.


In [6]:
# Show the numpy array shape

A.shape

(3, 3)

The total number of elements in the array is given by the attribute <code>size</code>.


In [7]:
# Show the numpy array size

A.size

9

<hr>


## Accessing different elements of a Numpy Array


We can use rectangular brackets to access the different elements of the array. The correspondence between the rectangular brackets and the list and the rectangular representation is shown in the following figure for a 3x3 array:  


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">


We can access the 2nd-row, 3rd column as shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


 We simply use the square brackets and the indices corresponding to the element we would like:


In [8]:
# Access the element on the second row and third column

A[1, 2]

23

 We can also use the following notation to obtain the elements: 


In [9]:
# Access the element on the second row and third column

A[1][2]

23

 Consider the elements shown in the following figure 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFF.png" width="400">


We can access the element as follows: 


In [10]:
# Access the element on the first row and first column

A[0][0]

11

We can also use slicing in numpy arrays. Consider the following figure. We would like to obtain the first two columns in the first row


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


 This can be done with the following syntax: 


In [11]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

Similarly, we can obtain the first two rows of the 3rd column as follows:


In [12]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

Corresponding to the following figure: 


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="400"><br />


Specifying the data type while declaring np array 

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [14]:
# create a numpy array of Zeros
x = np.zeros((4,5)) # 4,5 is the shape 4 is the no of rows and 5 is the no of columns
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# array of a particular value
z = np.full((5,4),5) # 5,4 is the shape and 5 is the number u want in array 
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
# create an identity matrix in this all the diagonal vlue is 1 and other value is 0 
a = np.eye(5) #i identity matrix no of rows and column is equal so we use 5 to define 5 rows and 5 column 
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create a numpy array with random values
b = np.random.random((3,4)) #3,4 is the shape 
print(b) # it generate random values but all the value is in between 0 and 1

[[0.53486736 0.46751275 0.93682629 0.97573704]
 [0.54081351 0.71615067 0.63418524 0.98755946]
 [0.7824099  0.80696814 0.81991614 0.2322799 ]]


In [19]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))  #3,5 is the shape and it generate a random integer array between 10 to 100
print(c)

[[79 51 28 72 26]
 [79 90 71 88 76]
 [14 80 91 12 33]]


In [20]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5) # 10 to 30 is the range where we get random values and 5 is the number of values required 
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)# 10 to 30 is the range where we get the random values and 5 is the step after which we get values
print(e)

[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

## Basic Operations


We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>X</code> and <code>Y</code> is shown in the following figure:


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">


The numpy array is given by <code>X</code> and <code>Y</code>


In [23]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [24]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

 We can add the numpy arrays as follows.


In [25]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [26]:
print(X+Y)
print('\n')
print(X-Y)
print('\n')
print(X*Y)
print('\n')
print(X/Y)
print('\n')

[[3 1]
 [1 3]]


[[-1 -1]
 [-1 -1]]


[[2 0]
 [0 2]]


[[0.5 0. ]
 [0.  0.5]]




In [36]:
print(np.add(X,Y))
print('\n')
print(np.subtract(X,Y))
print('\n')
print(np.multiply(X,Y))
print('\n')
print(np.divide(X,Y))
print('\n')

[[3 1]
 [1 3]]


[[-1 -1]
 [-1 -1]]


[[2 0]
 [0 2]]


[[0.5 0. ]
 [0.  0.5]]




Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>Y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">


We can perform the same operation in numpy as follows 


In [27]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [28]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">


We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:


In [29]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [30]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [31]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code> as follows:


First, we define matrix <code>A</code> and <code>B</code>:


In [32]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [33]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function <code>dot</code> to multiply the arrays together.


In [34]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [35]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

We use the numpy attribute <code>T</code> to calculate the transposed matrix


In [36]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [37]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
# transpose
trans = np.transpose(C)
print(trans)
print(trans.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


Reshaping an array

In [39]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 1 8]
 [6 6 7]]
(2, 3)


In [40]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 1]
 [8 6]
 [6 7]]
(3, 2)


<h2>Quiz on 2D Numpy Array</h2>


Consider the following list <code>a</code>, convert it to Numpy Array. 


In [41]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Click here for the solution</summary>

```python
A = np.array(a)
A
```

</details>


Calculate the numpy array size.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A.size
```

</details>


Access the element on the first row and first and second columns.


In [ ]:
# Write your code below and press Shift+Enter to execute


<details><summary>Click here for the solution</summary>

```python
A[0][0:2]
```

</details>


Perform matrix multiplication with the numpy arrays <code>A</code> and <code>B</code>.


In [ ]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

<details><summary>Click here for the solution</summary>

```python
X = np.dot(A,B)
X
```

</details>


<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. 
<hr>


## Author

<a href="https://www.linkedin.com/in/joseph-s-50398b136/" target="_blank">Joseph Santarcangelo</a>


## Other contributors

<a href="www.linkedin.com/in/jiahui-mavis-zhou-a4537814a">Mavis Zhou</a>


## Change Log


|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2023-11-02 | 2.2 | Abhishek Gagneja | Updated instructions |
| 2022-01-10  | 2.1  | Malika  | Removed the readme for GitShare|
| 2021-01-05 | 2.2 | Malika | Updated the solution for dot multiplication |
| 2020-09-09 | 2.1 | Malika | Updated the screenshot for first two rows of the 3rd column |
| 2020-08-26  | 2.0  | Lavanya | Moved lab to course repo in GitLab |



<hr/>

## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>
